Repository The-Greatest-Piggy/pigrest-server, pull requests merged in 2025-04, with the labels that each got.

#21 [feat] 공통 에러 핸들러 작성 #14
  .gitignore
  src/main/java/app/pigrest/exception/CustomException.java
  src/main/java/app/pigrest/exception/GlobalExceptionHandler.java
  src/main/resources/application.yaml
Labels: feat

#22 [fix] application.yaml 복구
  src/main/resources/application.yaml
Labels: bug

#23 [feat] 사용자 인증 시스템 구현
  build.gradle
  src/main/java/app/pigrest/auth/controller/AuthController.java
  src/main/java/app/pigrest/auth/dto/request/CheckUsernameRequest.java
  src/main/java/app/pigrest/auth/dto/request/LoginRequest.java
  src/main/java/app/pigrest/auth/dto/request/RegisterRequest.java
  src/main/java/app/pigrest/auth/dto/response/CheckUsernameResponse.java
  src/main/java/app/pigrest/auth/dto/response/LoginResponse.java
  src/main/java/app/pigrest/auth/dto/response/RegisterResponse.java
  src/main/java/app/pigrest/auth/model/Auth.java
  src/main/java/app/pigrest/auth/model/CustomUser.java
  src/main/java/app/pigrest/auth/repository/AuthRepository.java
  src/main/java/app/pigrest/auth/service/AuthService.java
  src/main/java/app/pigrest/auth/service/CustomUserDetailsService.java
  src/main/java/app/pigrest/auth/service/JwtService.java
  src/main/java/app/pigrest/auth/service/RedisService.java
  src/main/java/app/pigrest/config/JwtAuthenticationFilter.java
  src/main/java/app/pigrest/config/RedisConfig.java
  src/main/java/app/pigrest/config/SecurityConfig.java
  src/main/java/app/pigrest/member/model/Member.java
  src/main/resources/application-prod.yaml
  src/test/java/app/pigrest/content/controller/PinControllerTest.java
  src/test/resources/application.yaml
Labels: feat

#25 [test] 테스트 세팅 및 회원가입/로그인 테스트 작성
  build.gradle
  src/main/java/app/pigrest/auth/controller/AuthController.java
  src/main/java/app/pigrest/auth/dto/request/LoginRequest.java
  src/main/java/app/pigrest/auth/dto/request/RegisterRequest.java
  src/main/java/app/pigrest/auth/dto/response/RegisterResponse.java
  src/main/java/app/pigrest/auth/service/AuthService.java
  src/main/java/app/pigrest/exception/DuplicateResourceException.java
  src/main/java/app/pigrest/exception/GlobalExceptionHandler.java
  src/main/resources/application-prod.yaml
  src/test/java/app/pigrest/common/ApiResponseDocs.java
  src/test/java/app/pigrest/common/BaseControllerTest.java
  src/test/java/app/pigrest/controller/auth/AuthControllerTest.java
  src/test/java/app/pigrest/controller/auth/docs/LoginDocs.java
  src/test/java/app/pigrest/controller/auth/docs/RegisterDocs.java
  src/test/java/app/pigrest/controller/content/PinControllerTest.java
  src/test/java/app/pigrest/security/WithMockCustomUser.java
  src/test/java/app/pigrest/security/WithMockCustomUserSecurityContextFactory.java
Labels: documentation, test
